version: "3.9"

volumes:
  hf_cache:
  certbot_conf:
  certbot_www:

networks:
  app_net:
    driver: bridge

services:
  ################################
  # Gradio App
  ################################
  gradio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gradio
    expose:
      - "7860"
    volumes:
      - ./company_docs:/app/company_docs
      - ./data:/app/data
    networks:
      - app_net

  ################################
  # Nginx (HTTP only for now)
  ################################
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_conf:/etc/letsencrypt
      - ./certbot_www:/var/www/certbot
    networks:
      - app_net

  ################################
  # Certbot (manual run)
  ################################
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - app_net
